import type { DecisionArtifact } from "../domain/decision/types";

/**
 * Serializes a DecisionArtifact into a formal pre-trade risk audit memo (Markdown).
 */
export function exportDecisionArtifactAsMarkdown(artifact: DecisionArtifact): string {
  const trade = artifact.trade;
  const decision = artifact.decision;
  const market = artifact.marketState;
  const historical = artifact.historicalScenarios || artifact.thesisPosition?.historicalScenarios;
  const generatedTime = new Date(artifact.generatedAt).toUTCString();
  const basisBps = market.basisPct ? Math.round(market.basisPct * 10000) : 0;
  const isOffHours = market.sessionStatus === "WEEKEND" || market.sessionStatus === "OFF_HOURS" || market.sessionStatus === "HOLIDAY";

  const lines: string[] = [
    `# Bitget AI RedTeam Desk — Pre-Trade Decision Dossier`,
    ``,
    `**Artifact ID**: \`${artifact.artifactId}\`  `,
    `**Timestamp**: ${generatedTime}  `,
    `**Data Mode**: ${artifact.dataSource === "live" ? "🟢 LIVE MARKET FEED" : "🟡 DETERMINISTIC DEMO FIXTURE"}  `,
    `**Persona Lever**: ${artifact.riskToleranceApplied?.tolerance ?? "MODERATE"}  `,
    ``,
    `---`,
    ``,
    `## 1. Executive Verdict`,
    ``,
    `### **${decision.verdict}**`,
    ``,
    `**Proposed Trade**: \`${trade.direction.toUpperCase()} ${trade.asset} $${trade.positionSizeUsd.toLocaleString()}\`  `,
    `**Session State**: \`${market.sessionStatus}\` (Off-Hours: ${isOffHours ? "YES" : "NO"})  `,
    `**Off-Hours Basis Gap**: \`${basisBps} bps\`  `,
    ``,
    `### Primary Decision Reasons:`,
    ...decision.reasons.map((r) => `- **[${r.code}]**: ${r.message}`),
    ``,
    `---`,
    ``,
    `## 2. Quantitative Tail Stress Tests`,
    ``,
    `| Scenario ID | Shock Description | Est. PnL (USD) | Return % | Status |`,
    `| :--- | :--- | :--- | :--- | :--- |`,
    ...artifact.scenarios.map((s) => {
      const pnlUsd = s.estimatedPnlUsd !== null ? `$${s.estimatedPnlUsd.toLocaleString()}` : "N/A";
      const pnlPct = s.estimatedPnlPct !== null ? `${(s.estimatedPnlPct * 100).toFixed(1)}%` : "N/A";
      const status = s.estimatedPnlUsd !== null && s.estimatedPnlUsd < -100 ? "⚠️ STRESSED" : "✅ PASS";
      return `| \`${s.id}\` | ${s.description} | ${pnlUsd} | ${pnlPct} | ${status} |`;
    }),
    ``,
    `---`,
    ``,
    `## 3. Empirical Historical Precedent Match (Track 3 Sub-theme)`,
    ``
  ];

  if (historical && historical.precedents && historical.precedents.length > 0) {
    const metrics = historical.empiricalMetrics;
    lines.push(
      `**Match Confidence**: \`${historical.matchConfidence} MATCH\` (\`${historical.matchedAsset}\`)  `,
      `**Empirical Basis Shift**: \`${metrics.averageBasisShiftBps > 0 ? "+" : ""}${metrics.averageBasisShiftBps} bps\`  `,
      `**Max Historical Drawdown**: \`${metrics.maxHistoricalDrawdownPct}%\`  `,
      `**Estimated Re-Anchor Window**: \`${metrics.estimatedReAnchorHours} hours\`  `,
      ``,
      `### Matched Historical Events:`,
      ...historical.precedents.map((evt) =>
        `- **${evt.eventName}** (${evt.date}): ${evt.description}\n  *Empirical Outcome*: Drawdown ${evt.peakDrawdownPct}%, Re-Anchor ${evt.reAnchorHours}h, Basis Shift ${evt.basisShiftBps > 0 ? "+" : ""}${evt.basisShiftBps} bps`
      ),
      ``
    );
  } else {
    lines.push(`*No historical gap precedents matched for current trade parameters.*`, ``);
  }

  lines.push(
    `---`,
    ``,
    `## 4. Actionable Change Conditions to Upgrade Verdict`,
    ``,
    ...decision.changeConditions.map((cond, idx) => `${idx + 1}. ${cond}`),
    ``,
    `---`,
    ``,
    `## 5. Provenance & Audit Trail (${artifact.provenance.length} Verified Records)`,
    ``,
    `| Record ID | Type | Source / Model | Observation Time |`,
    `| :--- | :--- | :--- | :--- |`,
    ...artifact.provenance.slice(0, 15).map((p) =>
      `| \`${p.id}\` | \`${p.type}\` | ${p.source || p.modelIdentity || "Deterministic Engine"} | ${p.observedAt || p.retrievedAt || "N/A"} |`
    ),
    artifact.provenance.length > 15 ? `*... and ${artifact.provenance.length - 15} additional audit records in full JSON artifact.*` : ``,
    ``,
    `---`,
    `*Generated by Bitget AI RedTeam Desk (Track 3: AI Trading Desk — Decision Stress Testing).*`
  );

  return lines.join("\n");
}

/**
 * Serializes a DecisionArtifact into formatted JSON for API/audit ingestion.
 */
export function exportDecisionArtifactAsJson(artifact: DecisionArtifact): string {
  return JSON.stringify(artifact, null, 2);
}

/**
 * Browser helper to trigger a file download.
 */
export function downloadFile(filename: string, content: string, mimeType: string = "text/plain"): void {
  if (typeof window === "undefined") return;
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

/**
 * Browser helper to copy content to clipboard.
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  if (typeof navigator === "undefined" || !navigator.clipboard) return false;
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}
