/**
 * Bitget Signal - Agent Integration Contract
 * 
 * As per PRE24-03, the @bitget-ai/bitget-signal package is designed for AI hosts (Claude Code, Codex, OpenClaw).
 * The web application does NOT directly call the public MCP server.
 * Instead, this module defines the integration contract and import/bridge format for AI hosts.
 * 
 * Integration Contract:
 * 1. The web application generates a `SignalRequest` based on relevance routing.
 * 2. An external AI host (e.g., Claude Code) reads the request and invokes the corresponding Markdown Skills.
 *    - The AI host uses its MCP configuration to contact `https://datahub.noxiaohao.com/mcp`.
 * 3. The AI host formats the results as an array of `NormalizedResearchObservation` objects 
 *    and writes them to the `bridgePath` (e.g., a JSON file).
 * 4. This bridge reads the JSON file to ingest the observations back into the Decision Desk.
 * 
 * Supported Skills & Triggers:
 * - macro-analyst (Trigger: "Fed rate", "yield curve", "macro")
 * - market-intel (Trigger: "whales", "ETF flows", "cycle")
 * - sentiment-analyst (Trigger: "greedy", "fearful", "funding rate")
 * - technical-analysis (Trigger: "overbought", "support/resistance")
 * - news-briefing (Trigger: "news", "catalyst")
 */

import { existsSync } from "node:fs";
import { readFile, writeFile, unlink } from "node:fs/promises";
import { resolve } from "node:path";
import { tmpdir } from "node:os";
import type { NormalizedResearchObservation, ResearchProvider, ResearchProviderStatus } from "./types.js";

export interface SignalRequest {
  asset: string;
  thesis: string;
  requestedCapabilities: string[];
}

export class BitgetSignalAgentBridge implements ResearchProvider {
  readonly providerId = "bitget-signal-agent-bridge";
  private bridgePath: string;

  constructor(bridgePath: string = "signal-bridge-output.json") {
    // Write to /tmp in Vercel/Next.js environments to prevent read-only filesystem errors
    // and avoid Turbopack whole-project tracing warnings.
    this.bridgePath = resolve(tmpdir(), bridgePath);
  }

  async getStatus(): Promise<ResearchProviderStatus> {
    // Since this is a file-based bridge for an AI host, it's considered available
    // if the bridge mechanism is configured (we assume AVAILABLE for the contract).
    return "AVAILABLE";
  }

  private determineRelevance(thesis: string): string[] {
    const requested: string[] = [];
    const t = thesis.toLowerCase();

    // Implement relevance routing
    if (t.includes("macro") || t.includes("fed") || t.includes("rate") || t.includes("yield")) {
      requested.push("macro-analyst");
    }
    if (t.includes("on-chain") || t.includes("institutional") || t.includes("whale") || t.includes("flow")) {
      requested.push("market-intel");
    }
    if (t.includes("news") || t.includes("event") || t.includes("catalyst")) {
      requested.push("news-briefing");
    }
    if (t.includes("sentiment") || t.includes("positioning") || t.includes("funding") || t.includes("oi") || t.includes("greed")) {
      requested.push("sentiment-analyst");
    }
    if (t.includes("technical") || t.includes("support") || t.includes("resistance") || t.includes("rsi") || t.includes("trend")) {
      requested.push("technical-analysis");
    }

    // Default to news and intel if nothing specific is matched
    if (requested.length === 0) {
      requested.push("news-briefing", "market-intel");
    }

    return requested;
  }

  async getObservations(asset: string, topic?: string): Promise<NormalizedResearchObservation[]> {
    const thesis = topic ?? "";
    const requestedCapabilities = this.determineRelevance(thesis);

    // Write the request payload to disk for the AI host to intercept
    const request: SignalRequest = {
      asset,
      thesis,
      requestedCapabilities,
    };
    
    try {
      const inputPath = this.bridgePath.replace("-output.json", "-input.json");
      await writeFile(inputPath, JSON.stringify(request, null, 2), "utf-8");
    } catch (err) {
      console.warn("[BitgetSignalAgentBridge] Failed to write bridge request file", err);
    }
    
    // Attempt to read the bridge file output generated by the AI host
    if (existsSync(this.bridgePath)) {
      try {
        const content = await readFile(this.bridgePath, "utf-8");
        const observations = JSON.parse(content) as NormalizedResearchObservation[];
        
        // Ensure observations indicate which signal produced them and bound their size
        const results = observations.map(obs => ({
          ...obs,
          providerId: this.providerId,
          summary: obs.summary.substring(0, 500) // Bound response size
        }));

        // Clean up the output file to prevent stale data reuse on subsequent runs
        try {
          await unlink(this.bridgePath);
        } catch (e) {}

        return results;
      } catch (err) {
        console.warn("[BitgetSignalAgentBridge] Failed to parse bridge file", err);
      }
    }

    // Since the web app isn't actually executing the HTTP request to the MCP server,
    // and this is just the contract/bridge implementation, we return empty if the AI
    // host hasn't provided the bridge file.
    return [];
  }
}
